### ISSUE TITLE
feat: Add right & left shadows support

### ISSUE THREAD

**Issue by diosney** [mrmlnc/material-shadows#2]

**Comment by diosney** [comment]
This is useful for the navigation drawers (aka sidebars) and other vertical stuff.

**Comment by mrmlnc** [comment]
Thanks for Issue and idea. I will be doing this very soon. If you wish can send a PR.

**Comment by mrmlnc** [comment]
You have an example where you use vertical shadow?

I ask this because frameworks based on material design (for example [Materialize](http://materializecss.com/)) use for vertical staff a combination of shadow, which fully complies with mixin `.z-depth()`.

Example from Materialize:

``` css
.side-nav {
  box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
}
```

Use this mixin library:

``` less
.test {
  .z-depth();
}

// output
.test {
  box-shadow: 0 2px 10px 0 rgba(0, 0, 0, 0.12), 0 2px 5px rgba(0, 0, 0, 0.16);
}
```

As a result, there is no difference. Documentation material design also says nothing about the vertical shadows.

The [official framework of Google](http://www.getmdl.io/) also uses the same shadow for horizontal and vertical parts.
